### ISSUE TITLE
Words don't have enough space between them

### ISSUE THREAD

**Issue by ludo237** [gsora/nibberbot#19]
## Problem

When typing words are not correctly spaced in between

![image](https://user-images.githubusercontent.com/921500/31620610-f950f5d2-b297-11e7-928c-fde85b00bed4.png)

In this image, for instance, the last word is spaced correctly

![image](https://user-images.githubusercontent.com/921500/31620621-005183b0-b298-11e7-8498-867e47df12cf.png)

## Possible resolution 

Add more space between words

**Comment by gsora** [comment]
Interesting.

How many spaces nibberbot should add? Just one?

I was thinking 4 at least.

**Comment by ludo237** [comment]
Tests are necessary in order to fill up this discrepancy

**Comment by ludo237** [comment]
Also I hereby suggest to add at least for white space in order to preserve the readability.

**Comment by gsora** [comment]
Yeah, 4 might be enough but since this is a per-person agreement, adding a parameter might be the best choice.

I'll work on this in a couple hours.

**Comment by ludo237** [comment]
I do approve your decision sir

**Comment by gsora** [comment]
Closed because of e78446c
