### ISSUE TITLE
ℹ️'D JUST Lℹ️KE T🅾️ ℹ️NTE®JE©T F🅾️® 🅰️ M🅾️MENT.

### ISSUE THREAD

**Issue by dottorblaster** [gsora/nibberbot#6]
ℹ️'D JUST Lℹ️KE T🅾️ ℹ️NTE®JE©T F🅾️® 🅰️ M🅾️MENT. WH🅰️T Y🅾️U’®E ®EFE®®ℹ️N🅱️ T🅾️ 🅰️S Lℹ️NU❌, ℹ️S ℹ️N F🅰️©T, 🅱️NU/Lℹ️NU❌, 🅾️® 🅰️S ℹ️’VE ®E©ENTLY T🅰️KEN T🅾️ ©🅰️LLℹ️N🅱️ ℹ️T, 🅱️NU 🅿️LUS Lℹ️NU❌. Lℹ️NU❌ ℹ️S N🅾️T 🅰️N 🅾️🅿️E®🅰️Tℹ️N🅱️ SYSTEM UNT🅾️ ℹ️TSELF, 🅱️UT ®🅰️THE® 🅰️N🅾️THE® F®EE ©🅾️M🅿️🅾️NENT 🅾️F 🅰️ FULLY FUN©Tℹ️🅾️Nℹ️N🅱️ 🅱️NU SYSTEM M🅰️DE USEFUL 🅱️Y THE 🅱️NU ©🅾️®ELℹ️🅱️S, SHELL UTℹ️Lℹ️Tℹ️ES 🅰️ND Vℹ️T🅰️L SYSTEM ©🅾️M🅿️🅾️NENTS ©🅾️M🅿️®ℹ️Sℹ️N🅱️ 🅰️ FULL 🅾️S 🅰️S DEFℹ️NED 🅱️Y 🅿️🅾️Sℹ️❌.
M🅰️NY ©🅾️M🅿️UTE® USE®S ®UN 🅰️ M🅾️Dℹ️Fℹ️ED VE®Sℹ️🅾️N 🅾️F THE 🅱️NU SYSTEM EVE®Y D🅰️Y, Wℹ️TH🅾️UT ®E🅰️Lℹ️Zℹ️N🅱️ ℹ️T. TH®🅾️U🅱️H 🅰️ 🅿️E©ULℹ️🅰️® TU®N 🅾️F EVENTS, THE VE®Sℹ️🅾️N 🅾️F 🅱️NU WHℹ️©H ℹ️S Wℹ️DELY USED T🅾️D🅰️Y ℹ️S 🅾️FTEN ©🅰️LLED “Lℹ️NU❌”, 🅰️ND M🅰️NY 🅾️F ℹ️TS USE®S 🅰️®E N🅾️T 🅰️W🅰️®E TH🅰️T ℹ️T ℹ️S 🅱️🅰️Sℹ️©🅰️LLY THE 🅱️NU SYSTEM, DEVEL🅾️🅿️ED 🅱️Y THE 🅱️NU 🅿️®🅾️JE©T. THE®E ®E🅰️LLY ℹ️S 🅰️ Lℹ️NU❌, 🅰️ND THESE 🅿️E🅾️🅿️LE 🅰️®E USℹ️N🅱️ ℹ️T, 🅱️UT ℹ️T ℹ️S JUST 🅰️ 🅿️🅰️®T 🅾️F THE SYSTEM THEY USE.
Lℹ️NU❌ ℹ️S THE KE®NEL: THE 🅿️®🅾️🅱️®🅰️M ℹ️N THE SYSTEM TH🅰️T 🅰️LL🅾️©🅰️TES THE M🅰️©Hℹ️NE’S ®ES🅾️U®©ES T🅾️ THE 🅾️THE® 🅿️®🅾️🅱️®🅰️MS TH🅰️T Y🅾️U ®UN. THE KE®NEL ℹ️S 🅰️N ESSENTℹ️🅰️L 🅿️🅰️®T 🅾️F 🅰️N 🅾️🅿️E®🅰️Tℹ️N🅱️ SYSTEM, 🅱️UT USELESS 🅱️Y ℹ️TSELF; ℹ️T ©🅰️N 🅾️NLY FUN©Tℹ️🅾️N ℹ️N THE ©🅾️NTE❌T 🅾️F 🅰️ ©🅾️M🅿️LETE 🅾️🅿️E®🅰️Tℹ️N🅱️ SYSTEM. Lℹ️NU❌ ℹ️S N🅾️®M🅰️LLY USED ℹ️N ©🅾️M🅱️ℹ️N🅰️Tℹ️🅾️N Wℹ️TH THE 🅱️NU 🅾️🅿️E®🅰️Tℹ️N🅱️ SYSTEM: THE WH🅾️LE SYSTEM ℹ️S 🅱️🅰️Sℹ️©🅰️LLY 🅱️NU Wℹ️TH Lℹ️NU❌ 🅰️DDED, 🅾️® 🅱️NU/Lℹ️NU❌. 🅰️LL THE S🅾️-©🅰️LLED “Lℹ️NU❌” Dℹ️ST®ℹ️🅱️UTℹ️🅾️NS 🅰️®E ®E🅰️LLY Dℹ️ST®ℹ️🅱️UTℹ️🅾️NS 🅾️F 🅱️NU/Lℹ️NU❌.

**Comment by gsora** [comment]
I'm sorry, this software is not licensed under GPL.

Closing.
